/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as ExpensesRouteRouteImport } from './routes/expenses/route'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as ExpensesBudgetsRouteImport } from './routes/expenses/budgets'
import { Route as ExpensesCategoriesRouteImport } from './routes/expenses/categories'
import { Route as ExpensesInsightsRouteImport } from './routes/expenses/insights'
import { Route as ExpensesMembersRouteImport } from './routes/expenses/members'
import { Route as ExpensesTransactionsRouteImport } from './routes/expenses/transactions'
import { Route as SystemActivityRouteImport } from './routes/system/activity'
import { Route as WealthIndexRouteImport } from './routes/wealth/index'
import { Route as WealthOauthCallbackRouteImport } from './routes/wealth/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRouteRoute = ExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesBudgetsRoute = ExpensesBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesCategoriesRoute = ExpensesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesInsightsRoute = ExpensesInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesMembersRoute = ExpensesMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesTransactionsRoute = ExpensesTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const SystemActivityRoute = SystemActivityRouteImport.update({
  id: '/system/activity',
  path: '/system/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WealthIndexRoute = WealthIndexRouteImport.update({
  id: '/wealth/',
  path: '/wealth/',
  getParentRoute: () => rootRouteImport,
} as any)
const WealthOauthCallbackRoute = WealthOauthCallbackRouteImport.update({
  id: '/wealth/oauth/callback',
  path: '/wealth/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/checklists': typeof ChecklistsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/expenses/budgets': typeof ExpensesBudgetsRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/insights': typeof ExpensesInsightsRoute
  '/expenses/members': typeof ExpensesMembersRoute
  '/expenses/transactions': typeof ExpensesTransactionsRoute
  '/system/activity': typeof SystemActivityRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/wealth/': typeof WealthIndexRoute
  '/wealth/oauth/callback': typeof WealthOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/expenses/budgets': typeof ExpensesBudgetsRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/insights': typeof ExpensesInsightsRoute
  '/expenses/members': typeof ExpensesMembersRoute
  '/expenses/transactions': typeof ExpensesTransactionsRoute
  '/system/activity': typeof SystemActivityRoute
  '/expenses': typeof ExpensesIndexRoute
  '/wealth': typeof WealthIndexRoute
  '/wealth/oauth/callback': typeof WealthOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/checklists': typeof ChecklistsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/expenses/budgets': typeof ExpensesBudgetsRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/insights': typeof ExpensesInsightsRoute
  '/expenses/members': typeof ExpensesMembersRoute
  '/expenses/transactions': typeof ExpensesTransactionsRoute
  '/system/activity': typeof SystemActivityRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/wealth/': typeof WealthIndexRoute
  '/wealth/oauth/callback': typeof WealthOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/checklists'
    | '/settings'
    | '/tasks'
    | '/expenses/budgets'
    | '/expenses/categories'
    | '/expenses/insights'
    | '/expenses/members'
    | '/expenses/transactions'
    | '/system/activity'
    | '/expenses/'
    | '/wealth/'
    | '/wealth/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklists'
    | '/settings'
    | '/tasks'
    | '/expenses/budgets'
    | '/expenses/categories'
    | '/expenses/insights'
    | '/expenses/members'
    | '/expenses/transactions'
    | '/system/activity'
    | '/expenses'
    | '/wealth'
    | '/wealth/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/checklists'
    | '/settings'
    | '/tasks'
    | '/expenses/budgets'
    | '/expenses/categories'
    | '/expenses/insights'
    | '/expenses/members'
    | '/expenses/transactions'
    | '/system/activity'
    | '/expenses/'
    | '/wealth/'
    | '/wealth/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRouteRoute: typeof ExpensesRouteRouteWithChildren
  ChecklistsRoute: typeof ChecklistsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  SystemActivityRoute: typeof SystemActivityRoute
  WealthIndexRoute: typeof WealthIndexRoute
  WealthOauthCallbackRoute: typeof WealthOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/budgets': {
      id: '/expenses/budgets'
      path: '/budgets'
      fullPath: '/expenses/budgets'
      preLoaderRoute: typeof ExpensesBudgetsRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/categories': {
      id: '/expenses/categories'
      path: '/categories'
      fullPath: '/expenses/categories'
      preLoaderRoute: typeof ExpensesCategoriesRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/insights': {
      id: '/expenses/insights'
      path: '/insights'
      fullPath: '/expenses/insights'
      preLoaderRoute: typeof ExpensesInsightsRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/members': {
      id: '/expenses/members'
      path: '/members'
      fullPath: '/expenses/members'
      preLoaderRoute: typeof ExpensesMembersRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/transactions': {
      id: '/expenses/transactions'
      path: '/transactions'
      fullPath: '/expenses/transactions'
      preLoaderRoute: typeof ExpensesTransactionsRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/system/activity': {
      id: '/system/activity'
      path: '/system/activity'
      fullPath: '/system/activity'
      preLoaderRoute: typeof SystemActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/': {
      id: '/wealth/'
      path: '/wealth'
      fullPath: '/wealth/'
      preLoaderRoute: typeof WealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/oauth/callback': {
      id: '/wealth/oauth/callback'
      path: '/wealth/oauth/callback'
      fullPath: '/wealth/oauth/callback'
      preLoaderRoute: typeof WealthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExpensesRouteRouteChildren {
  ExpensesBudgetsRoute: typeof ExpensesBudgetsRoute
  ExpensesCategoriesRoute: typeof ExpensesCategoriesRoute
  ExpensesInsightsRoute: typeof ExpensesInsightsRoute
  ExpensesMembersRoute: typeof ExpensesMembersRoute
  ExpensesTransactionsRoute: typeof ExpensesTransactionsRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

const ExpensesRouteRouteChildren: ExpensesRouteRouteChildren = {
  ExpensesBudgetsRoute: ExpensesBudgetsRoute,
  ExpensesCategoriesRoute: ExpensesCategoriesRoute,
  ExpensesInsightsRoute: ExpensesInsightsRoute,
  ExpensesMembersRoute: ExpensesMembersRoute,
  ExpensesTransactionsRoute: ExpensesTransactionsRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}

const ExpensesRouteRouteWithChildren = ExpensesRouteRoute._addFileChildren(
  ExpensesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRouteRoute: ExpensesRouteRouteWithChildren,
  ChecklistsRoute: ChecklistsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  SystemActivityRoute: SystemActivityRoute,
  WealthIndexRoute: WealthIndexRoute,
  WealthOauthCallbackRoute: WealthOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
