/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRestrictedRouteImport } from './routes/access-restricted'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as ExpensesRouteRouteImport } from './routes/expenses/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as ExpensesBudgetsRouteImport } from './routes/expenses/budgets'
import { Route as ExpensesCategoriesRouteImport } from './routes/expenses/categories'
import { Route as ExpensesInsightsRouteImport } from './routes/expenses/insights'
import { Route as ExpensesMembersRouteImport } from './routes/expenses/members'
import { Route as ExpensesTransactionsRouteImport } from './routes/expenses/transactions'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAccessRouteRouteImport } from './routes/settings/access/route'
import { Route as SystemActivityRouteImport } from './routes/system/activity'
import { Route as WealthIndexRouteImport } from './routes/wealth/index'
import { Route as SettingsAccessIndexRouteImport } from './routes/settings/access/index'
import { Route as SettingsAccessPermissionsRouteImport } from './routes/settings/access/permissions'
import { Route as SettingsAccessRolesRouteImport } from './routes/settings/access/roles'
import { Route as SettingsAccessUsersRouteImport } from './routes/settings/access/users'
import { Route as WealthOauthCallbackRouteImport } from './routes/wealth/oauth/callback'
import { Route as SettingsAccessRolesRoleKeyRouteImport } from './routes/settings/access/roles.$roleKey'
import { Route as SettingsAccessUsersIdRouteImport } from './routes/settings/access/users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRestrictedRoute = AccessRestrictedRouteImport.update({
  id: '/access-restricted',
  path: '/access-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRouteRoute = ExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesBudgetsRoute = ExpensesBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesCategoriesRoute = ExpensesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesInsightsRoute = ExpensesInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesMembersRoute = ExpensesMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const ExpensesTransactionsRoute = ExpensesTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ExpensesRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccessRouteRoute = SettingsAccessRouteRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SystemActivityRoute = SystemActivityRouteImport.update({
  id: '/system/activity',
  path: '/system/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WealthIndexRoute = WealthIndexRouteImport.update({
  id: '/wealth/',
  path: '/wealth/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessIndexRoute = SettingsAccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsAccessRouteRoute,
} as any)
const SettingsAccessPermissionsRoute =
  SettingsAccessPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => SettingsAccessRouteRoute,
  } as any)
const SettingsAccessRolesRoute = SettingsAccessRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsAccessRouteRoute,
} as any)
const SettingsAccessUsersRoute = SettingsAccessUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsAccessRouteRoute,
} as any)
const WealthOauthCallbackRoute = WealthOauthCallbackRouteImport.update({
  id: '/wealth/oauth/callback',
  path: '/wealth/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessRolesRoleKeyRoute =
  SettingsAccessRolesRoleKeyRouteImport.update({
    id: '/$roleKey',
    path: '/$roleKey',
    getParentRoute: () => SettingsAccessRolesRoute,
  } as any)
const SettingsAccessUsersIdRoute = SettingsAccessUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettingsAccessUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/access-restricted': typeof AccessRestrictedRoute
  '/checklists': typeof ChecklistsRoute
  '/tasks': typeof TasksRoute
  '/settings/access': typeof SettingsAccessRouteRouteWithChildren
  '/expenses/budgets': typeof ExpensesBudgetsRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/insights': typeof ExpensesInsightsRoute
  '/expenses/members': typeof ExpensesMembersRoute
  '/expenses/transactions': typeof ExpensesTransactionsRoute
  '/system/activity': typeof SystemActivityRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/wealth/': typeof WealthIndexRoute
  '/settings/access/permissions': typeof SettingsAccessPermissionsRoute
  '/settings/access/roles': typeof SettingsAccessRolesRouteWithChildren
  '/settings/access/users': typeof SettingsAccessUsersRouteWithChildren
  '/wealth/oauth/callback': typeof WealthOauthCallbackRoute
  '/settings/access/': typeof SettingsAccessIndexRoute
  '/settings/access/roles/$roleKey': typeof SettingsAccessRolesRoleKeyRoute
  '/settings/access/users/$id': typeof SettingsAccessUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-restricted': typeof AccessRestrictedRoute
  '/checklists': typeof ChecklistsRoute
  '/tasks': typeof TasksRoute
  '/expenses/budgets': typeof ExpensesBudgetsRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/insights': typeof ExpensesInsightsRoute
  '/expenses/members': typeof ExpensesMembersRoute
  '/expenses/transactions': typeof ExpensesTransactionsRoute
  '/system/activity': typeof SystemActivityRoute
  '/expenses': typeof ExpensesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/wealth': typeof WealthIndexRoute
  '/settings/access/permissions': typeof SettingsAccessPermissionsRoute
  '/settings/access/roles': typeof SettingsAccessRolesRouteWithChildren
  '/settings/access/users': typeof SettingsAccessUsersRouteWithChildren
  '/wealth/oauth/callback': typeof WealthOauthCallbackRoute
  '/settings/access': typeof SettingsAccessIndexRoute
  '/settings/access/roles/$roleKey': typeof SettingsAccessRolesRoleKeyRoute
  '/settings/access/users/$id': typeof SettingsAccessUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/access-restricted': typeof AccessRestrictedRoute
  '/checklists': typeof ChecklistsRoute
  '/tasks': typeof TasksRoute
  '/settings/access': typeof SettingsAccessRouteRouteWithChildren
  '/expenses/budgets': typeof ExpensesBudgetsRoute
  '/expenses/categories': typeof ExpensesCategoriesRoute
  '/expenses/insights': typeof ExpensesInsightsRoute
  '/expenses/members': typeof ExpensesMembersRoute
  '/expenses/transactions': typeof ExpensesTransactionsRoute
  '/system/activity': typeof SystemActivityRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/wealth/': typeof WealthIndexRoute
  '/settings/access/permissions': typeof SettingsAccessPermissionsRoute
  '/settings/access/roles': typeof SettingsAccessRolesRouteWithChildren
  '/settings/access/users': typeof SettingsAccessUsersRouteWithChildren
  '/wealth/oauth/callback': typeof WealthOauthCallbackRoute
  '/settings/access/': typeof SettingsAccessIndexRoute
  '/settings/access/roles/$roleKey': typeof SettingsAccessRolesRoleKeyRoute
  '/settings/access/users/$id': typeof SettingsAccessUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/settings'
    | '/access-restricted'
    | '/checklists'
    | '/tasks'
    | '/settings/access'
    | '/expenses/budgets'
    | '/expenses/categories'
    | '/expenses/insights'
    | '/expenses/members'
    | '/expenses/transactions'
    | '/system/activity'
    | '/expenses/'
    | '/settings/'
    | '/wealth/'
    | '/settings/access/permissions'
    | '/settings/access/roles'
    | '/settings/access/users'
    | '/wealth/oauth/callback'
    | '/settings/access/'
    | '/settings/access/roles/$roleKey'
    | '/settings/access/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-restricted'
    | '/checklists'
    | '/tasks'
    | '/expenses/budgets'
    | '/expenses/categories'
    | '/expenses/insights'
    | '/expenses/members'
    | '/expenses/transactions'
    | '/system/activity'
    | '/expenses'
    | '/settings'
    | '/wealth'
    | '/settings/access/permissions'
    | '/settings/access/roles'
    | '/settings/access/users'
    | '/wealth/oauth/callback'
    | '/settings/access'
    | '/settings/access/roles/$roleKey'
    | '/settings/access/users/$id'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/settings'
    | '/access-restricted'
    | '/checklists'
    | '/tasks'
    | '/settings/access'
    | '/expenses/budgets'
    | '/expenses/categories'
    | '/expenses/insights'
    | '/expenses/members'
    | '/expenses/transactions'
    | '/system/activity'
    | '/expenses/'
    | '/settings/'
    | '/wealth/'
    | '/settings/access/permissions'
    | '/settings/access/roles'
    | '/settings/access/users'
    | '/wealth/oauth/callback'
    | '/settings/access/'
    | '/settings/access/roles/$roleKey'
    | '/settings/access/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRouteRoute: typeof ExpensesRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AccessRestrictedRoute: typeof AccessRestrictedRoute
  ChecklistsRoute: typeof ChecklistsRoute
  TasksRoute: typeof TasksRoute
  SystemActivityRoute: typeof SystemActivityRoute
  WealthIndexRoute: typeof WealthIndexRoute
  WealthOauthCallbackRoute: typeof WealthOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-restricted': {
      id: '/access-restricted'
      path: '/access-restricted'
      fullPath: '/access-restricted'
      preLoaderRoute: typeof AccessRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/budgets': {
      id: '/expenses/budgets'
      path: '/budgets'
      fullPath: '/expenses/budgets'
      preLoaderRoute: typeof ExpensesBudgetsRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/categories': {
      id: '/expenses/categories'
      path: '/categories'
      fullPath: '/expenses/categories'
      preLoaderRoute: typeof ExpensesCategoriesRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/insights': {
      id: '/expenses/insights'
      path: '/insights'
      fullPath: '/expenses/insights'
      preLoaderRoute: typeof ExpensesInsightsRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/members': {
      id: '/expenses/members'
      path: '/members'
      fullPath: '/expenses/members'
      preLoaderRoute: typeof ExpensesMembersRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/expenses/transactions': {
      id: '/expenses/transactions'
      path: '/transactions'
      fullPath: '/expenses/transactions'
      preLoaderRoute: typeof ExpensesTransactionsRouteImport
      parentRoute: typeof ExpensesRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/system/activity': {
      id: '/system/activity'
      path: '/system/activity'
      fullPath: '/system/activity'
      preLoaderRoute: typeof SystemActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wealth/': {
      id: '/wealth/'
      path: '/wealth'
      fullPath: '/wealth/'
      preLoaderRoute: typeof WealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access/': {
      id: '/settings/access/'
      path: '/'
      fullPath: '/settings/access/'
      preLoaderRoute: typeof SettingsAccessIndexRouteImport
      parentRoute: typeof SettingsAccessRouteRoute
    }
    '/settings/access/permissions': {
      id: '/settings/access/permissions'
      path: '/permissions'
      fullPath: '/settings/access/permissions'
      preLoaderRoute: typeof SettingsAccessPermissionsRouteImport
      parentRoute: typeof SettingsAccessRouteRoute
    }
    '/settings/access/roles': {
      id: '/settings/access/roles'
      path: '/roles'
      fullPath: '/settings/access/roles'
      preLoaderRoute: typeof SettingsAccessRolesRouteImport
      parentRoute: typeof SettingsAccessRouteRoute
    }
    '/settings/access/users': {
      id: '/settings/access/users'
      path: '/users'
      fullPath: '/settings/access/users'
      preLoaderRoute: typeof SettingsAccessUsersRouteImport
      parentRoute: typeof SettingsAccessRouteRoute
    }
    '/wealth/oauth/callback': {
      id: '/wealth/oauth/callback'
      path: '/wealth/oauth/callback'
      fullPath: '/wealth/oauth/callback'
      preLoaderRoute: typeof WealthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access/roles/$roleKey': {
      id: '/settings/access/roles/$roleKey'
      path: '/$roleKey'
      fullPath: '/settings/access/roles/$roleKey'
      preLoaderRoute: typeof SettingsAccessRolesRoleKeyRouteImport
      parentRoute: typeof SettingsAccessRolesRoute
    }
    '/settings/access/users/$id': {
      id: '/settings/access/users/$id'
      path: '/$id'
      fullPath: '/settings/access/users/$id'
      preLoaderRoute: typeof SettingsAccessUsersIdRouteImport
      parentRoute: typeof SettingsAccessUsersRoute
    }
  }
}

interface ExpensesRouteRouteChildren {
  ExpensesBudgetsRoute: typeof ExpensesBudgetsRoute
  ExpensesCategoriesRoute: typeof ExpensesCategoriesRoute
  ExpensesInsightsRoute: typeof ExpensesInsightsRoute
  ExpensesMembersRoute: typeof ExpensesMembersRoute
  ExpensesTransactionsRoute: typeof ExpensesTransactionsRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

const ExpensesRouteRouteChildren: ExpensesRouteRouteChildren = {
  ExpensesBudgetsRoute: ExpensesBudgetsRoute,
  ExpensesCategoriesRoute: ExpensesCategoriesRoute,
  ExpensesInsightsRoute: ExpensesInsightsRoute,
  ExpensesMembersRoute: ExpensesMembersRoute,
  ExpensesTransactionsRoute: ExpensesTransactionsRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}

const ExpensesRouteRouteWithChildren = ExpensesRouteRoute._addFileChildren(
  ExpensesRouteRouteChildren,
)

interface SettingsAccessRolesRouteChildren {
  SettingsAccessRolesRoleKeyRoute: typeof SettingsAccessRolesRoleKeyRoute
}

const SettingsAccessRolesRouteChildren: SettingsAccessRolesRouteChildren = {
  SettingsAccessRolesRoleKeyRoute: SettingsAccessRolesRoleKeyRoute,
}

const SettingsAccessRolesRouteWithChildren =
  SettingsAccessRolesRoute._addFileChildren(SettingsAccessRolesRouteChildren)

interface SettingsAccessUsersRouteChildren {
  SettingsAccessUsersIdRoute: typeof SettingsAccessUsersIdRoute
}

const SettingsAccessUsersRouteChildren: SettingsAccessUsersRouteChildren = {
  SettingsAccessUsersIdRoute: SettingsAccessUsersIdRoute,
}

const SettingsAccessUsersRouteWithChildren =
  SettingsAccessUsersRoute._addFileChildren(SettingsAccessUsersRouteChildren)

interface SettingsAccessRouteRouteChildren {
  SettingsAccessPermissionsRoute: typeof SettingsAccessPermissionsRoute
  SettingsAccessRolesRoute: typeof SettingsAccessRolesRouteWithChildren
  SettingsAccessUsersRoute: typeof SettingsAccessUsersRouteWithChildren
  SettingsAccessIndexRoute: typeof SettingsAccessIndexRoute
}

const SettingsAccessRouteRouteChildren: SettingsAccessRouteRouteChildren = {
  SettingsAccessPermissionsRoute: SettingsAccessPermissionsRoute,
  SettingsAccessRolesRoute: SettingsAccessRolesRouteWithChildren,
  SettingsAccessUsersRoute: SettingsAccessUsersRouteWithChildren,
  SettingsAccessIndexRoute: SettingsAccessIndexRoute,
}

const SettingsAccessRouteRouteWithChildren =
  SettingsAccessRouteRoute._addFileChildren(SettingsAccessRouteRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsAccessRouteRoute: typeof SettingsAccessRouteRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccessRouteRoute: SettingsAccessRouteRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRouteRoute: ExpensesRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AccessRestrictedRoute: AccessRestrictedRoute,
  ChecklistsRoute: ChecklistsRoute,
  TasksRoute: TasksRoute,
  SystemActivityRoute: SystemActivityRoute,
  WealthIndexRoute: WealthIndexRoute,
  WealthOauthCallbackRoute: WealthOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
